name: Build and Push Docker Image
permissions: {}
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Output Docker image version

env:
  REGISTRY: ghcr.io

jobs:
  build-docker-and-push:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/gytsto/vagrant-under-docker-${{ inputs.version }}
        build-args: |
          REVISION=${{ github.sha }}

  build-docker-on-branch:
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/gytsto/debug-vagrant-under-docker:${{ github.sha }}
        build-args: |
          REVISION=${{ github.sha }}